# Generated by Django 4.2.10 on 2024-11-24 17:55

# migration para agregar species a DB.
# También agregado al formato de tabla para mostrar desde el http.

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='species',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
